### ISSUE TITLE
Cannot Start in Administrator Mode

### ISSUE THREAD

**Issue by UthredRagnarson** [NexovaDev/UpdateHub#245]
### Description of issue: When I go into the MS Store Apps option I get the message stating "This feature requires administrator mode.
Please restart the app in administrator mode."

But when I do I still get the same message. This is even though the shortcut i am using has the option to 'Run in Admin Mode' checked  or if I run from the Start Menu option right clicking and selecting 'Run in Admin Mode'.

Please advise as to what I am doing wrong or how I get the app to run in Admin mode.

Many thanks.
### Debug Info: 
```
App version: 2.2.1
WinGet version: 1.5.2201
OS version: 22621.2283
Node version: 18.16.1
Electron version: 26.2.1
Chrome version: 116.0.5845.188
Device ID: 1cf5a995-ef5d-409a-8211-a228dc385694
```

**Comment by KK-Designs** [comment]
We have found out why the issue is occurring and are working on a fix. A temporary workaround would be to force close the app by pressing the shift key and then clicking the X icon in the windows title bar or by right-clicking the icon in the system tray and clicking "Close" and then relaunching the app as administrator.

**Comment by UthredRagnarson** [comment]
Hi KK-Designs

Thanks for the prompt response. I tried what has been suggested and can confirm that this worked.

All the best

Uthred

**Comment by KK-Designs** [comment]
This workaround is no longer needed as of [v2.3.1](https://github.com/NexovaDev/UpdateHub/releases/tag/v2.3.1).
