### ISSUE TITLE
Auto-update/update of UpdateHub feature doesn't work in Windows 11 ARM64

### ISSUE THREAD

**Issue by Corsair-63** [NexovaDev/UpdateHub#254]
while my W11 x64 installations auto-update the software (UpdateHub) without any problem in my two installations of windows 11 Pro ARM64, when it tells me that there is a new program update (UpdateHub) it keeps in something like 64 Kb updating but it doesn't go further.
if I close the program and I download the latest update and run it, there is no problem, and it works as desired.

**Comment by Corsair-63** [comment]
Windows 11 Pro ARM64.

from attached screenshot the update doesn't go forward in windows x64 version there is no problem.
![sshot-1](https://github.com/KK-Designs/UpdateHub/assets/76228638/018be6f8-20f4-457c-8243-05e961760e4f)

**Comment by KK-Designs** [comment]
Does it go really slow or does it just freeze entirely?

**Comment by Corsair-63** [comment]
> Does it go really slow or does it just freeze entirely?

most of the times it the window blinks and doesn't move, it tries to download but no success.
another time start to download at grease lighting speed of 1 kb every lot of seconds but at last doesn't downloads too much.

all the times I must follow the link "View in Browser" kill the program, download a run manually the program.

**Comment by KK-Designs** [comment]
It's happening to me too on a 64-bit copy of Windows 11, updating from 2.2.1 to the latest. It only seems to happen if you update via the "Update" button in the popup, not the one in the sidebar. It's not supposed to show "Invalid Date" as the date, which would be a clue. Waiting for the auto-update interval works just fine (requires restart if you already pressed the manual button). My guess is that the code that is used to update from that button is messed up. After further investigation, I found two major issues:

1. The ID for that update button is the same as the one that updates outdated apps, so if that occurs on the outdated app list page, it would error out.

2. This is the one that's causing the error. Notice how in the picture it's calling the `updateAppDev` function instead of the `updateApp` function? That means it's trying to download the executable from our development server (we had a dev server and a production channel). However, our dev channel server is permanently down as we do not need it anymore, it was used in the early pre-v1 stages of UpdateHub development to distribute builds across devices faster. So what's happening is that it's requesting a file from a server that doesn't exist, and then fails. The reason why it's able to download that 90kb is because of the way we turned off the server, we are just limiting HTTP traffic to a tiny bit. So it's maxing out at that point then timeouts. The explanation for the "Invalid Date" is because, at the time when the dev server was being used, that Release date feature didn't exist yet. That was added in v2.0.0, way after the dev server was closed.
![image](https://github.com/KK-Designs/UpdateHub/assets/71038229/255d124d-eab7-45a5-8ef2-67773d514686)

![image](https://github.com/KK-Designs/UpdateHub/assets/71038229/9086baab-d720-404d-ab39-f2a87b9537d0)


## This will be fixed in the next release of UpdateHub

**Comment by KK-Designs** [comment]
Should be fixed in the latest release 👍
